<?php
$page_title = "Superadmin Dashboard";
$required_role = "superadmin";
require_once '../includes/auth_check.php';
require_once '../includes/db_connect.php'; 

// Fetch data for filter dropdowns
$receptionists_result = $conn->query("SELECT id, username FROM users WHERE role = 'receptionist' ORDER BY username");
$doctors_result = $conn->query("SELECT id, doctor_name FROM referral_doctors WHERE is_active = 1 ORDER BY doctor_name");

require_once '../includes/header.php';
?>
<!-- Include the new CSS and JS files for the sub-test feature -->
<link rel="stylesheet" href="../assets/css/doctor_subtest_details.css">
<script src="../assets/js/superadmin_dashboard_subtest.js"></script>
<main class="main-content">
    <div id="notification-corner"></div>
    <div class="content-header">
        <div class="header-container"><h1>Doctor Performance Report</h1></div>
        <p>Detailed breakdown of doctor referrals, test revenues, and payouts.</p>
        <p style="font-size: 13px; color: #4e73df; margin-top: 8px;">
            💡 <strong>Tip:</strong> Click on any doctor's name to view detailed subtest breakdown. 
            <span style="color: #1cc88a;">✓ All filters apply to both main table and subtest details.</span>
        </p>
    </div>

    <div class="page-card filter-bar">
        <form id="analytics-filter-form" class="filter-form-flex">
            <div class="form-group">
                <label for="start_date">Start Date</label>
                <input type="date" id="start_date" name="start_date" class="form-control" value="<?php echo date('Y-m-01'); ?>">
            </div>
            <div class="form-group">
                <label for="end_date">End Date</label>
                <input type="date" id="end_date" name="end_date" class="form-control" value="<?php echo date('Y-m-t'); ?>">
            </div>
            <div class="form-group">
                <label for="receptionist_id">Receptionist</label>
                <select id="receptionist_id" name="receptionist_id" class="form-control">
                    <option value="">All</option>
                    <?php while($row = $receptionists_result->fetch_assoc()): ?>
                        <option value="<?php echo $row['id']; ?>"><?php echo htmlspecialchars($row['username']); ?></option>
                    <?php endwhile; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="doctor_id">Doctor</label>
                 <select id="doctor_id" name="doctor_id" class="form-control">
                    <option value="">All</option>
                    <?php while($row = $doctors_result->fetch_assoc()): ?>
                        <option value="<?php echo $row['id']; ?>">Dr. <?php echo htmlspecialchars($row['doctor_name']); ?></option>
                    <?php endwhile; ?>
                </select>
            </div>
            <!-- NEW SORT BY FILTER -->
            <div class="form-group">
                <label for="sort_by">Sort By</label>
                <select id="sort_by" name="sort_by" class="form-control">
                    <option value="net_amount">Net Amount</option>
                    <option value="gross_amount">Gross Amount</option>
                    <option value="total_test_count">Total Tests</option>
                </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Apply Filters</button>
            </div>
        </form>
    </div>

    <!-- NEW EXCEL-STYLE REPORT CONTAINER -->
    <div class="page-card">
        <div class="chart-header">
            <h3>Doctor-wise Performance Data</h3>
        </div>
        <div class="table-responsive">
            <table class="data-table" id="doctor-report-table">
                <thead id="report-table-header">
                    <!-- Header will be dynamically generated by PHP in ajax_dashboard_analytics.php and rendered by JS -->
                </thead>
                <tbody id="report-table-body">
                    <tr>
                        <td colspan="100%" style="text-align: center; padding: 40px;">
                            <div class="spinner"></div>
                            <p>Loading report data...</p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>

<style>
.spinner {
    border: 4px solid #f3f3f3;
    border-top: 4px solid #4e73df;
    border-radius: 50%;
    width: 40px;
    height: 40px;
    animation: spin 1s linear infinite;
    margin: 0 auto 10px;
}
@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
.table-responsive {
    overflow-x: auto;
}

/* Doctor row styles */
.doctor-row {
    transition: background-color 0.2s ease;
}
.doctor-row:hover {
    background-color: #f8f9fc !important;
}
.doctor-name-cell:hover {
    text-decoration: underline;
}
.expand-icon {
    display: inline-block;
    transition: transform 0.3s ease;
    color: #4e73df;
    font-size: 12px;
}

/* Detail row styles */
.detail-row td {
    background: #f8f9fc !important;
    border-top: none !important;
}
.detail-content {
    animation: slideDown 0.3s ease-out;
}
@keyframes slideDown {
    from {
        opacity: 0;
        transform: translateY(-10px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

/* Subtest details styling */
.subtest-details-container {
    margin: 0;
}
.subtest-category-card {
    transition: transform 0.2s ease, box-shadow 0.2s ease;
}
.subtest-category-card:hover {
    transform: translateY(-2px);
    box-shadow: 0 3px 8px rgba(0,0,0,0.15) !important;
}
.subtest-item:last-child {
    border-bottom: none !important;
}
</style>

<?php require_once '../includes/footer.php'; ?>
